### ISSUE TITLE
Example of how to use pywinrt with a custom winrt runtime class

### ISSUE THREAD

**Issue by rileymjohnson** [pywinrt/pywinrt#23]
Is it possible to use pywinrt with my own winrt runtime class or only with existing classes? If it's possible, is there an example of this somewhere? I know that the process goes something like this:
- Use the midl compiler to produce a .windmd file
- Use the cppwinrt tool, which produces a folder of files
- Use the pywinrt tool to generate another folder of files

After that, I'm not really sure what to do. I think that I'm supposed to copy one folder into another but I'm not sure which/where. Also, it's unclear to me whether I should be using the cppwinrt tool's -component flag. Thanks for your help.

**Comment by dlech** [comment]
I haven't tried this, but I would start with a copy of the [winsdk](https://github.com/pywinrt/python-winsdk) repo and change the `winsdk` namespace to your own namespace everywhere. Then change the `cppwinrt.exe` and `pywinrt.exe` options in `generate.ps1` as needed. Since I haven't done it before, I'm not clear on what options are needed either.

Another thing I am curious about is how it handles dependencies. I'm guessing that it will include anything from the Windows SDK that is directly referenced, but if you need other APIs from the Windows SDK as well it could be an issue. I'm not sure that you could use your own generated library and `winsdk` at the same time. Eventually, I would like to address https://github.com/pywinrt/python-winsdk/issues/1 to make it easier to bring your own components without having to reproduce the full Windows SDK as well.

**Comment by dlech** [comment]
In the last few weeks, I have been working on some major change in the `multi-package` branch to make it possible to create your own package without having to also duplicate the entire runtime and dependencies. There is a `TestComponent` that can be used as an example of how to create bindings for your own component package.
