### ISSUE TITLE
Could not install pywinrt package into project that targets "native,Version=v0.0"

### ISSUE THREAD

**Issue by rileymjohnson** [pywinrt/pywinrt#24]
I've been trying to use pywinrt to create bindings for custom components, but I've not had a ton of success. In particular, I have not been able to get pywinrt to work in Visual Studio at all because NuGet says it cannot install pywinrt. The full error is:

`Could not install package 'Microsoft.Windows.PyWinRT 0.9.190508.3'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

These are the steps I took:

1. Create a new Visual Studio project of type `Windows Runtime Component (WinUI 3)`
2. Set the target version to `Windows 11, Version 22H2 (10.0; Build 22621)`
3. Set the minimum version to `Windows 10, Version 1809 (10.0, Build 17763)`
4. Attempt to install pywinrt via the Visual Studio GUI (i.e., `Tools > NuGet Package Manager > Manage NuGet Packages for Solution...`)

What am I doing wrong here? Could I be using the wrong version? Or perhaps I'm targeting the wrong version(s) of Windows? I want to mention that the versions I selected are the defaults; I don't have any particular attachment to them. Another idea I had is that I'm using the wrong project type, but I'm really not sure.

**Comment by dlech** [comment]
This package is distributed under the name `PyWinRT`, not `Microsoft.Windows.PyWinRT`.

**Comment by rileymjohnson** [comment]
Oh whoops. Wrong repo. Sorry about that.

I can't see that package in visual studio btw. I can see it on the NuGet website and install it via the NuGet CLI, but nothing comes up when I search for it in the Visual Studio NuGet window.

**Comment by dlech** [comment]
You have to check "Include prerelase" for it to show up (only beta version released so far).

**Comment by dlech** [comment]
It looks like the package doesn't use the correct format (i.e. it uses `bin/` instead of `tools` to package the executable. Also, it should probably also have a `build/` directory with some `.props` and or `.targets` files for integration with msbuild project files.

Reference: https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package

Happy to take a pull request to fix this. Source is here: https://github.com/pywinrt/pywinrt/tree/main/nuget

Also, FYI, I'm working on https://github.com/pywinrt/python-winsdk/issues/1 which will make it much easier to package custom components. Stay tuned...

**Comment by dlech** [comment]
Alternately, we could consider distributing the tool with PyPI instead of Nuget since the work I am doing is going to be distributing required header files that way already.

**Comment by rileymjohnson** [comment]
I'll look into fixing the NuGet package. I'm quite interested using custom WinRT components within Python.

**Comment by rileymjohnson** [comment]
@dlech I figured out how to load a WinRT component from a DLL without registration. I haven't yet integrated this with PyWinRT, but it is an important step. Here's a [gist](https://gist.github.com/rileymjohnson/d3e559d6be154db9ceb8549a78584b56) in case that's helpful to you.

**Comment by dlech** [comment]
Thanks for sharing your findings. I finally got around to looking into it. It turns out that CppWinRT had some similar code already. So it was just a matter of adding the location of your .dll to the search path. I've added a feature to PyWinRT to handle this, so I think we can call this one closed.
